# Cumulative Attention Calculation

In [1]:
import torch
import numpy as np

In [24]:
A1 = np.array([
    [
        [0.8, 0.0, 0.2, 0.0],
        [1.0, 0.0, 0.0, 0.0],
        [0.5, 0.5, 0.0, 0.0],
        [0.0, 0.0, 0.9, 0.1]
    ],
    [
        [1.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 1.0, 0.0],
        [1.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.1, 0.9]
    ]
])
A1.shape

(2, 4, 4)

In [67]:
A2 = np.array([
    [
        [0.1, 0.9, 0.0, 0.0],
        [0.0, 0.0, 1.0, 0.0],
        [1.0, 0.0, 0.0, 0.0],
        [0.0, 1.0, 0.0, 0.0]
    ],
    [
        [1.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 1.0],
        [0.0, 0.0, 1.0, 0.0],
        [0.0, 0.5, 0.0, 0.5]
    ]
])
A2.shape

(2, 4, 4)

In [71]:
A3 = np.array([
    [
        [0.0, 0.0, 1.0, 0.0],
        [1.0, 0.0, 0.0, 0.0],
        [0.5, 0.5, 0.0, 0.0],
        [0.0, 0.0, 0.9, 0.1]
    ]
])

In [25]:
ans = A1.sum(axis=0)/(A1.shape[0]*4.0)
ans

array([[0.225 , 0.    , 0.025 , 0.    ],
       [0.125 , 0.    , 0.125 , 0.    ],
       [0.1875, 0.0625, 0.    , 0.    ],
       [0.    , 0.    , 0.125 , 0.125 ]])

In [49]:
ans.sum(axis=0)

array([0.5375, 0.0625, 0.275 , 0.125 ])

In [52]:
def CumulativeAttention(Atts):
    l = Atts.__len__()
    s = Atts[1].shape[-1]
    As = np.zeros(shape=(l, s, s))
    C = np.zeros(shape=(l,s))

    i = 0
    for A in Atts:
        As[i] = A.sum(axis=0)/(A.shape[0])
        if i > 0:
            As[i] = np.matmul(As[i],As[i-1])
        C[i] = As[i].sum(axis=0)/s
        i = i+1

    return (As, C)

In [72]:
As = [A1, A2, A3]
(A, C) = CumulativeAttention(As)
C

array([[0.5375  , 0.0625  , 0.275   , 0.125   ],
       [0.57375 , 0.0625  , 0.27    , 0.09375 ],
       [0.718125, 0.075   , 0.1725  , 0.034375]])

In [54]:
C.sum(axis=1)

array([1., 1., 1.])

In [76]:
c_4 = 0.9*1.0*0.5 + 0.9*0.5*0.1 + 0.1*1.0*0.5 + 0.1*0.5*0.1
c_4*0.5*0.5/4.0

0.034375

In [78]:
4.3/8

0.5375